/**
 * Phase 0 attribution.
 *
 * A participant forwards `/readiness-snapshot/?p=CODE`. The code says
 * who sent the visitor. It says nothing about who the visitor is, it is
 * never shown to them, and no other identifier is derived from it.
 *
 * Four states, in the order they can occur:
 *
 *   1. The link is forwarded. An opaque code in a URL. Nobody knows who
 *      received it, and nothing about the recipient is embedded in it.
 *   2. The Snapshot is completed. A completion is recorded against the
 *      code. We know a completion happened on that code. Not who.
 *   3. The visitor identifies themselves, by choosing to use the
 *      follow-up form. That is a separate, voluntary act, and it is the
 *      only route by which we come to know who they are.
 *   4. An introduction is made. An ordinary introduction, with ordinary
 *      permission.
 *
 * WHAT THIS FILE MUST NEVER GROW INTO. No fingerprinting. No IP-based
 * identification. No third-party enrichment. No analytics event carrying
 * the code. The states above are a commitment, not a description of the
 * current implementation, so anything that would let us infer a
 * recipient identity without their choosing belongs nowhere near here.
 *
 * SILENCE ON FAILURE. An unknown or malformed code produces exactly the
 * experience of no code at all. A visible rejection would tell a
 * recipient that a code had been tried, which discloses the referral
 * before the participant has chosen to.
 */

/** Query parameter carrying the code. */
const PARAM = 'p';

/** Session-scoped, first party. Not localStorage: it must not outlive the visit. */
const KEY = 'intv-snapshot-p';

/**
 * Exactly eight lowercase alphanumerics. Codes are generated by
 * `scripts/generate-attribution-codes.mjs` and issued individually.
 */
const SHAPE = /^[a-z0-9]{8}$/;

/** Reads the code, if the current visit has one. Empty string otherwise. */
export function attributionCode(): string {
  try {
    const stored = sessionStorage.getItem(KEY) ?? '';
    return SHAPE.test(stored) ? stored : '';
  } catch {
    return '';
  }
}

/**
 * Captures the code on landing and removes it from the address bar.
 *
 * Called once, before anything else on the page runs. Removing the
 * parameter keeps the code out of the one place the visitor could read
 * it, and out of anything they might copy, bookmark or share.
 */
export function captureAttribution(): void {
  let url: URL;
  try {
    url = new URL(window.location.href);
  } catch {
    return;
  }

  const raw = url.searchParams.get(PARAM);
  if (raw === null) return;

  // Whatever happens next, the parameter goes. A malformed value is
  // discarded as silently as a valid one is stored.
  url.searchParams.delete(PARAM);
  try {
    const query = url.searchParams.toString();
    window.history.replaceState(
      window.history.state,
      '',
      `${url.pathname}${query ? `?${query}` : ''}${url.hash}`,
    );
  } catch {
    /* a blocked history API must not break the visit */
  }

  if (!SHAPE.test(raw)) return;

  try {
    sessionStorage.setItem(KEY, raw);
  } catch {
    /* a full or blocked sessionStorage costs attribution, not the visit */
  }
}

/**
 * Exported for the unit test. The regular expression is the whole of the
 * validation rule, so the test asserts against the rule rather than a copy.
 */
export function isValidCode(value: string): boolean {
  return SHAPE.test(value);
}
