/**
 * Phase 0 attribution.
 *
 * A participant forwards `/readiness-snapshot/?p=CODE`. The code says
 * who sent the visitor. It says nothing about who the visitor is, it is
 * never shown to them, and no other identifier is derived from it.
 *
 * Four states, in the order they can occur:
 *
 *   1. The link is forwarded. An opaque code in a URL. Nobody knows who
 *      received it, and nothing about the recipient is embedded in it.
 *      Attribution is accepted only for an issued code; a well-formed
 *      but unknown value is treated as an unattributed visit.
 *   2. The Snapshot is completed. A completion is recorded against the
 *      code. We know a completion happened on that code. Not who.
 *   3. The visitor identifies themselves, by choosing to use the
 *      follow-up form. That is a separate, voluntary act, and it is the
 *      only route by which we come to know who they are.
 *   4. An introduction is made. An ordinary introduction, with ordinary
 *      permission.
 *
 * NOTHING IS WRITTEN TO THE VISITOR'S DEVICE.
 *
 * The code lives in the variable below, for as long as the page object
 * lives, and goes when the tab is closed or the page is reloaded. That
 * is a deliberate Phase 0 choice, not an oversight.
 *
 * Writing the code to `sessionStorage` would be storage on terminal
 * equipment under PECR regulation 6, for our purposes rather than the
 * visitor's, so the strictly-necessary exemption would be arguable
 * rather than clear. A variable is not storage on terminal equipment,
 * which removes the question instead of answering it. See section 9 of
 * `internal/legitimate-interests-assessment.md`.
 *
 * THE COST, ACCEPTED. A visitor who reloads the page loses their
 * attribution, and their completion is then recorded as no completion
 * at all rather than as somebody else's. The Snapshot answers survive a
 * reload because they are held in `sessionStorage`, so the two now
 * behave differently and a reloaded visit will under-count. At six
 * participants the debrief carries the weight and a missed completion
 * is a known, one-directional error. Revisit if attribution is ever
 * load bearing commercially.
 *
 * WHAT THIS FILE MUST NEVER GROW INTO. No fingerprinting. No IP-based
 * identification. No third-party enrichment. No analytics event carrying
 * the code. The states above are a commitment, not a description of the
 * current implementation, so anything that would let us infer a
 * recipient identity without their choosing belongs nowhere near here.
 *
 * SILENCE ON FAILURE. An unknown or malformed code produces exactly the
 * experience of no code at all. A visible rejection would tell a
 * recipient that a code had been tried, which discloses the referral
 * before the participant has chosen to.
 */

/** Query parameter carrying the code. */
const PARAM = 'p';

/**
 * Exactly eight lowercase alphanumerics. Codes are generated by
 * `scripts/generate-attribution-codes.mjs` and issued individually.
 *
 * The shape is necessary and not sufficient. See `ISSUED` below.
 */
const SHAPE = /^[a-z0-9]{8}$/;

/**
 * The six codes issued for Phase 0. Attribution is accepted for these
 * and for nothing else.
 *
 * Shape alone is not a code. Until 19 August 2026 this file accepted
 * any well-formed value, so `?p=test0000` produced a real completion
 * record for a code nobody was ever issued. That is an integrity
 * problem, not a security one: arbitrary values must not be able to
 * manufacture observations in an experiment with six data points.
 *
 * A set of six strings, deliberately. No database, no lookup, no
 * registry. If the cohort ever grows past a size a person can read,
 * that is the moment to reconsider, and not before.
 *
 * These ship in the client bundle, which is fine and was decided
 * knowingly. The codes are opaque, carry no participant identity, and
 * guard a count rather than an entitlement.
 *
 * Exported only so the unit test asserts against this list rather than
 * against a second copy of it that could drift.
 */
export const ISSUED: ReadonlySet<string> = new Set([
  'ffsw9hg2',
  'd4s32d6p',
  '8pqmv6gc',
  'gn5kppwx',
  '77r78c4n',
  's2ghbvv2',
]);

/**
 * The whole of the persistence layer, kept behind two functions so the
 * decision above can be reconsidered without touching anything else.
 *
 * `read` and `write` are the only places that know where the code
 * lives. Pointing them at `sessionStorage`, a session cookie or
 * anything else is a change to these four lines and to the privacy
 * notice, and to nothing in the flow.
 */
let held = '';

function read(): string {
  return held;
}

function write(value: string): void {
  held = value;
}

/** Reads the code, if the current page has one. Empty string otherwise. */
export function attributionCode(): string {
  const value = read();
  return isValidCode(value) ? value : '';
}

/**
 * Captures the code on landing and removes it from the address bar.
 *
 * Called once, before anything else on the page runs. Removing the
 * parameter keeps the code out of the one place the visitor could read
 * it, and out of anything they might copy, bookmark or share. It also
 * means a reload cannot recover it, which is the accepted cost above.
 */
export function captureAttribution(): void {
  let url: URL;
  try {
    url = new URL(window.location.href);
  } catch {
    return;
  }

  const raw = url.searchParams.get(PARAM);
  if (raw === null) return;

  // Whatever happens next, the parameter goes. A malformed value is
  // discarded as silently as a valid one is kept.
  url.searchParams.delete(PARAM);
  try {
    const query = url.searchParams.toString();
    window.history.replaceState(
      window.history.state,
      '',
      `${url.pathname}${query ? `?${query}` : ''}${url.hash}`,
    );
  } catch {
    /* a blocked history API must not break the visit */
  }

  if (!isValidCode(raw)) return;
  write(raw);
}

/**
 * The whole of the validation rule: correct format, and actually issued.
 *
 * Exported for the unit test, so the test asserts against the rule
 * rather than against a copy of it.
 */
export function isValidCode(value: string): boolean {
  return SHAPE.test(value) && ISSUED.has(value);
}

/** Exported for the unit test, which needs a clean page between cases. */
export function resetAttributionForTest(): void {
  write('');
}
